### ISSUE TITLE
The tslint task overwrites the TypeScript package of the application

### ISSUE THREAD

**Issue by balassy** [urbanjs/tools#4]
I have an app that explicitly references TypeScript in the `package.json` with the version `2.1.5`. After running `npm install` the 2.1.5 version is installed into the `node_modules` folder, as expected.

However, when I run `gulp tslint` from UrbanJS, it logs `Installing missing dependencies... typescript@2.0.7` to the console, and overwrites the previously installed package in the `node_modules` folder.

The problem is that UrbanJS installs a version of TypeScript, that does not contain a feature required by the application. The expected behavior is that a developer tool (in this case UrbanJS) does not overwrite any package that is required by the application.

Thanks for fixing this issue.

**Comment by tamasmagedli** [comment]
Lazy dependency installation will be removed from urbanjs in version 2 and it won't cause any similar issue.
Until that, you can use the beta version of urbanjs (2.0.0-beta3) to get the latest TypeScript installed. 
I'll let you know once v2 is released.

**Comment by balassy** [comment]
Thank you very much, I really appreciate it!

**Comment by tamasmagedli** [comment]
Urbanjs@2 has been released; lazy dependency installation won't overwrite the packages from now on. I am closing this issue and let me know if you have any question about it.

**Comment by balassy** [comment]
Thanks a lot!
